import os
from decimal import Decimal
from uuid import uuid4

import pytest
from sqlalchemy import create_engine, inspect, insert, text

from app.workflow import initialize_workflow, sales_orders


@pytest.fixture()
def postgres_engine():
    database_url = os.getenv("WORKFLOW_TEST_DATABASE_URL")
    if not database_url:
        pytest.skip("WORKFLOW_TEST_DATABASE_URL is required for PostgreSQL integration tests")
    if not database_url.startswith(("postgresql://", "postgresql+psycopg://")):
        pytest.fail("WORKFLOW_TEST_DATABASE_URL must point to PostgreSQL")

    admin_engine = create_engine(database_url, pool_pre_ping=True)
    schema = f"workflow_test_{uuid4().hex}"
    quoted_schema = admin_engine.dialect.identifier_preparer.quote(schema)
    with admin_engine.begin() as connection:
        connection.execute(text(f"CREATE SCHEMA {quoted_schema}"))

    engine = create_engine(
        database_url,
        connect_args={"options": f"-csearch_path={schema}"},
        pool_pre_ping=True,
    )
    try:
        yield engine
    finally:
        engine.dispose()
        with admin_engine.begin() as connection:
            connection.execute(text(f"DROP SCHEMA {quoted_schema} CASCADE"))
        admin_engine.dispose()


def test_initialize_workflow_creates_postgresql_schema_and_generated_ids(postgres_engine):
    initialize_workflow(postgres_engine)

    inspector = inspect(postgres_engine)
    assert {
        "sales_orders",
        "sales_order_items",
        "delivery_notes",
        "delivery_note_items",
    }.issubset(inspector.get_table_names())

    columns = {column["name"]: column for column in inspector.get_columns("sales_orders")}
    assert columns["company_id"]["nullable"] is False
    assert columns["subtotal"]["type"].precision == 18
    assert columns["subtotal"]["type"].scale == 2

    with postgres_engine.begin() as connection:
        document_id = connection.execute(
            insert(sales_orders)
            .values(
                company_id=42,
                customer_id=7,
                order_date="2026-07-12",
                subtotal=Decimal("123.45"),
                grand_total=Decimal("123.45"),
            )
            .returning(sales_orders.c.id)
        ).scalar_one()
        row = connection.execute(
            text(
                "SELECT company_id, subtotal FROM sales_orders "
                "WHERE id = :id AND company_id = :company_id"
            ),
            {"id": document_id, "company_id": 42},
        ).mappings().one()

    assert document_id > 0
    assert row["company_id"] == 42
    assert row["subtotal"] == Decimal("123.45")


def test_initialize_workflow_upgrades_legacy_columns_to_numeric(postgres_engine):
    with postgres_engine.begin() as connection:
        connection.execute(text("CREATE TABLE quotes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"))
        connection.execute(text("CREATE TABLE quote_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"))
        connection.execute(text('CREATE TABLE returns (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)'))
        connection.execute(text("CREATE TABLE return_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"))

    initialize_workflow(postgres_engine)

    inspector = inspect(postgres_engine)
    quote_columns = {column["name"]: column for column in inspector.get_columns("quotes")}
    assert quote_columns["subtotal"]["type"].precision == 18
    assert quote_columns["subtotal"]["type"].scale == 2
    assert "company_id" in quote_columns

