"""Pluggable notification delivery seam with a safe default NoOp provider."""

from .archive import (
    MIN_RETENTION_DAYS,
    RetentionPolicyError,
    archive_all_companies,
    archive_disarmed_notifications,
    resolve_retention_days,
)
from .consents import (
    ConsentError,
    evaluate_consent,
    get_consent,
    list_consent_events,
    list_consents,
    normalize_msisdn,
    normalize_recipient,
    set_consent,
)
from .content_gate import ContentRejected, assert_content_allowed, is_content_allowed
from .provider import (
    NoOpNotificationProvider,
    NotificationProvider,
    NotificationResult,
    SimulationNotificationProvider,
    SmtpEmailNotificationProvider,
    TwilioNotificationProvider,
    WhatsAppNotificationProvider,
    get_notification_provider,
)
from .render import TemplateRenderError, build_content, content_hash, render_body
from .service import (
    InvalidTransitionError,
    NotificationApprovalError,
    NotificationBusyError,
    NotificationNotFoundError,
    NotificationNotRetryableError,
    approve_notification,
    assert_transition,
    backoff_delay_seconds,
    cancel_expired_verification_notifications,
    cancel_notification,
    claimable_notification_ids,
    disarm_rule_notifications,
    enqueue_notification,
    invalidate_approval,
    outbox_counters,
    schedule_retry,
    send_notification,
    stuck_processing_count,
)

__all__ = [
    "ConsentError",
    "ContentRejected",
    "InvalidTransitionError",
    "MIN_RETENTION_DAYS",
    "NoOpNotificationProvider",
    "NotificationApprovalError",
    "NotificationBusyError",
    "NotificationNotFoundError",
    "NotificationNotRetryableError",
    "NotificationProvider",
    "NotificationResult",
    "RetentionPolicyError",
    "SimulationNotificationProvider",
    "SmtpEmailNotificationProvider",
    "TemplateRenderError",
    "TwilioNotificationProvider",
    "WhatsAppNotificationProvider",
    "approve_notification",
    "archive_all_companies",
    "archive_disarmed_notifications",
    "assert_content_allowed",
    "assert_transition",
    "backoff_delay_seconds",
    "build_content",
    "cancel_expired_verification_notifications",
    "cancel_notification",
    "claimable_notification_ids",
    "content_hash",
    "disarm_rule_notifications",
    "enqueue_notification",
    "evaluate_consent",
    "get_consent",
    "get_notification_provider",
    "invalidate_approval",
    "is_content_allowed",
    "list_consent_events",
    "list_consents",
    "normalize_msisdn",
    "normalize_recipient",
    "outbox_counters",
    "render_body",
    "resolve_retention_days",
    "schedule_retry",
    "send_notification",
    "set_consent",
    "stuck_processing_count",
]
