import React from 'react';
import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Stack,Tab,Tabs,TextField,Typography} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';import SwapHorizIcon from '@mui/icons-material/SwapHoriz';import DeleteIcon from '@mui/icons-material/Delete';
import {GridColDef} from '@mui/x-data-grid';import ResponsiveTable from '../components/ResponsiveTable';import {api,money} from '../api';

const accountLabels:any={cash:'Kasa',bank:'Banka',pos:'POS'};
// CS3: çek/senet işlemleri /cek-senet-portfoyu sayfasına taşındı. Buradaki eski
// sekme hesap kimliğini tarayıcı istem kutusuyla soruyordu; artık yalnız bir
// bağlantıdır.
const CEK_SENET_ROTASI='/cek-senet-portfoyu';
const emptyAccount={name:'',account_type:'cash',currency:'TRY',opening_balance:0,bank_name:'',iban:'',is_active:true};
export default function Finance(){
 const location=useLocation();const navigate=useNavigate();
 // Dashboard hesap karti / son hareket satiri router state ile gelir: {accountId,transactionId}.
 const [focusAccountId,setFocusAccountId]=useState<number|null>(null),[focusTxnId,setFocusTxnId]=useState<number|null>(null);
 const [tab,setTab]=useState(0),[summary,setSummary]=useState<any>({accounts:[],totals:{},instruments:{}}),[txns,setTxns]=useState<any[]>([]),[error,setError]=useState('');
 const [accountOpen,setAccountOpen]=useState(false),[account,setAccount]=useState<any>(emptyAccount),[accountId,setAccountId]=useState<number|null>(null);
 const [txnOpen,setTxnOpen]=useState(false),[txn,setTxn]=useState<any>({account_id:'',txn_date:new Date().toISOString().slice(0,10),direction:'in',amount:0,category:'other',payment_method:'cash',description:''});
 const [transferOpen,setTransferOpen]=useState(false),[transfer,setTransfer]=useState<any>({source_account_id:'',target_account_id:'',txn_date:new Date().toISOString().slice(0,10),amount:0,description:''});
 const load=async()=>{try{setError('');const [s,t]=await Promise.all([api.get('/finance/summary'),api.get('/finance/transactions')]);setSummary(s.data);setTxns(t.data)}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{
  const state:any=location.state;
  if(!state)return;
  if(state.accountId||state.transactionId){
   setTab(1);
   setFocusAccountId(state.accountId?Number(state.accountId):null);
   setFocusTxnId(state.transactionId?Number(state.transactionId):null);
  }
  navigate(location.pathname,{replace:true,state:null});
 },[location.state,location.pathname,navigate]);
 const focusedTxns=useMemo(()=>{
  if(focusTxnId)return txns.filter(t=>Number(t.id)===focusTxnId);
  if(focusAccountId)return txns.filter(t=>Number(t.account_id)===focusAccountId);
  return txns;
 },[txns,focusAccountId,focusTxnId]);
 const focusLabel=focusTxnId?`Hareket #${focusTxnId}`:focusAccountId?(summary.accounts||[]).find((a:any)=>Number(a.id)===focusAccountId)?.name||`Hesap #${focusAccountId}`:'';
 const clearFocus=()=>{setFocusAccountId(null);setFocusTxnId(null)};
 const saveAccount=async()=>{try{if(accountId)await api.put(`/finance/accounts/${accountId}`,account);else await api.post('/finance/accounts',account);setAccountOpen(false);load()}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 const saveTxn=async()=>{try{await api.post('/finance/transactions',{...txn,account_id:Number(txn.account_id),amount:Number(txn.amount)});setTxnOpen(false);load()}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 const saveTransfer=async()=>{try{await api.post('/finance/transfers',{...transfer,source_account_id:Number(transfer.source_account_id),target_account_id:Number(transfer.target_account_id),amount:Number(transfer.amount)});setTransferOpen(false);load()}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 const accountCols=useMemo<GridColDef[]>(()=>[{field:'name',headerName:'Hesap',flex:1,minWidth:190},{field:'account_type',headerName:'Tür',width:110,valueFormatter:v=>accountLabels[v]||v},{field:'currency',headerName:'Para Birimi',width:105},{field:'opening_balance',headerName:'Açılış',width:130,valueFormatter:v=>money(v)},{field:'balance',headerName:'Güncel Bakiye',width:155,valueFormatter:v=>money(v)},{field:'transaction_count',headerName:'Hareket',width:90},{field:'actions',headerName:'',width:80,sortable:false,renderCell:p=><IconButton size="small" onClick={()=>{setAccountId(p.row.id);setAccount({...p.row});setAccountOpen(true)}}>✎</IconButton>}],[]);
 const txnCols=useMemo<GridColDef[]>(()=>[{field:'txn_date',headerName:'Tarih',width:120},{field:'account_name',headerName:'Hesap',width:190},{field:'direction',headerName:'Yön',width:90,renderCell:p=><Chip size="small" color={p.value==='in'?'success':'error'} label={p.value==='in'?'Giriş':'Çıkış'}/>},{field:'category',headerName:'Kategori',width:130},{field:'amount',headerName:'Tutar',width:140,valueFormatter:v=>money(v)},{field:'description',headerName:'Açıklama',flex:1,minWidth:240},{field:'reference_type',headerName:'Kaynak',width:110},{field:'actions',headerName:'',width:60,renderCell:p=>p.row.reference_type==='manual'?<IconButton color="error" size="small" onClick={async()=>{await api.delete(`/finance/transactions/${p.row.id}`);load()}}><DeleteIcon fontSize="small"/></IconButton>:null}],[]);
 return <Stack spacing={2}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Typography variant="h4" fontWeight={900}>Nakit Yönetimi</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="outlined" startIcon={<SwapHorizIcon/>} onClick={()=>setTransferOpen(true)}>Virman</Button><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>tab===0?(setAccountId(null),setAccount(emptyAccount),setAccountOpen(true)):tab===1?setTxnOpen(true):navigate(CEK_SENET_ROTASI)}>{tab===0?'Yeni Hesap':tab===1?'Yeni Hareket':'Çek / Senet Portföyü'}</Button></Stack></Stack>{error&&<Alert severity="error">{error}</Alert>}<Stack direction={{xs:'column',sm:'row'}} spacing={1}>{[['Kasa',summary.totals?.cash||0],['Banka',summary.totals?.bank||0],['POS',summary.totals?.pos||0],['Alınan Çek/Senet',summary.instruments?.received_open||0],['Verilen Çek/Senet',summary.instruments?.issued_open||0]].map(([label,value])=><Card key={String(label)} sx={{flex:1}}><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h6" fontWeight={900}>{money(Number(value))}</Typography></CardContent></Card>)}</Stack><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Hesaplar"/><Tab label="Hareketler"/><Tab label="Çek / Senet"/></Tabs>{tab===0&&<ResponsiveTable rows={summary.accounts||[]} columns={accountCols} cardTitle={r=>r.name} cardSubtitle={r=>accountLabels[r.account_type]} cardFields={[{label:'Bakiye',value:r=>money(r.balance)},{label:'Hareket',value:r=>r.transaction_count}]}/>} {tab===1&&<>{focusLabel&&<Chip sx={{alignSelf:'flex-start'}} color="primary" label={`Odak: ${focusLabel}`} onDelete={clearFocus}/>}<ResponsiveTable rows={focusedTxns} columns={txnCols} cardTitle={r=>r.account_name} cardSubtitle={r=>`${r.txn_date} · ${r.direction==='in'?'Giriş':'Çıkış'}`} cardFields={[{label:'Tutar',value:r=>money(r.amount)},{label:'Açıklama',value:r=>r.description||'-'}]}/></>} {tab===2&&<Card variant="outlined" data-testid="cek-senet-yonlendirme"><CardContent><Stack spacing={1.5} alignItems="flex-start"><Typography fontWeight={800}>Çek ve senetler artık ayrı bir ekranda</Typography><Typography variant="body2" color="text.secondary">Portföy listesi, vade takvimi, bordro girişi ve tahsil / ciro / karşılıksız / iade işlemleri Çek / Senet Portföyü sayfasındadır.</Typography><Button variant="contained" onClick={()=>navigate(CEK_SENET_ROTASI)}>Çek / Senet Portföyüne Git</Button></Stack></CardContent></Card>}
 <Dialog open={accountOpen} onClose={()=>setAccountOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{accountId?'Hesap Düzenle':'Yeni Finans Hesabı'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Hesap Adı" value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/><TextField select label="Hesap Türü" value={account.account_type} onChange={e=>setAccount({...account,account_type:e.target.value})}>{Object.entries(accountLabels).map(([k,v])=><MenuItem key={k} value={k}>{String(v)}</MenuItem>)}</TextField><TextField label="Açılış Bakiyesi" type="number" value={account.opening_balance} onChange={e=>setAccount({...account,opening_balance:Number(e.target.value)})}/>{account.account_type==='bank'&&<><TextField label="Banka" value={account.bank_name||''} onChange={e=>setAccount({...account,bank_name:e.target.value})}/><TextField label="IBAN" value={account.iban||''} onChange={e=>setAccount({...account,iban:e.target.value})}/></>}</Stack></DialogContent><DialogActions><Button onClick={()=>setAccountOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={saveAccount}>Kaydet</Button></DialogActions></Dialog>
 <Dialog open={txnOpen} onClose={()=>setTxnOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Yeni Kasa/Banka Hareketi</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField select label="Hesap" value={txn.account_id} onChange={e=>setTxn({...txn,account_id:e.target.value})}>{summary.accounts?.filter((a:any)=>a.is_active).map((a:any)=><MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>)}</TextField><TextField select label="Yön" value={txn.direction} onChange={e=>setTxn({...txn,direction:e.target.value})}><MenuItem value="in">Para Girişi</MenuItem><MenuItem value="out">Para Çıkışı</MenuItem></TextField><TextField label="Tutar" type="number" value={txn.amount} onChange={e=>setTxn({...txn,amount:Number(e.target.value)})}/><TextField label="Tarih" type="date" value={txn.txn_date} onChange={e=>setTxn({...txn,txn_date:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Kategori" value={txn.category} onChange={e=>setTxn({...txn,category:e.target.value})}/><TextField label="Açıklama" value={txn.description} onChange={e=>setTxn({...txn,description:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setTxnOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={saveTxn}>Kaydet</Button></DialogActions></Dialog>
 <Dialog open={transferOpen} onClose={()=>setTransferOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Hesaplar Arası Virman</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField select label="Kaynak Hesap" value={transfer.source_account_id} onChange={e=>setTransfer({...transfer,source_account_id:e.target.value})}>{summary.accounts?.filter((a:any)=>a.is_active).map((a:any)=><MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>)}</TextField><TextField select label="Hedef Hesap" value={transfer.target_account_id} onChange={e=>setTransfer({...transfer,target_account_id:e.target.value})}>{summary.accounts?.filter((a:any)=>a.is_active).map((a:any)=><MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>)}</TextField><TextField label="Tutar" type="number" value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:Number(e.target.value)})}/><TextField label="Tarih" type="date" value={transfer.txn_date} onChange={e=>setTransfer({...transfer,txn_date:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Açıklama" value={transfer.description} onChange={e=>setTransfer({...transfer,description:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setTransferOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={saveTransfer}>Virman Yap</Button></DialogActions></Dialog>
 </Stack>
}
