import React from 'react';
import {useEffect,useState} from 'react';
import {Alert,Box,Card,CardContent,Chip,CircularProgress,Grid,LinearProgress,Stack,Typography} from '@mui/material';
import {useNavigate} from 'react-router-dom';
import AnalyticsIcon from '@mui/icons-material/Analytics';
import {api,money} from '../api';

type Insight={
 generated_at:string;
 sales_trend:{current_30_days:number;previous_30_days:number;change_percent:number|null};
 overdue:{count:number;total:number};
 inactive_customers:any[];critical_products:any[];profitable_products:any[];
 recommendations:{severity:'success'|'info'|'warning'|'error';title:string;detail:string;path:string}[];
};
export default function Insights(){const [data,setData]=useState<Insight|null>(null);const [error,setError]=useState('');const nav=useNavigate();useEffect(()=>{api.get('/analytics/insights').then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||e.message))},[]);if(error)return <Alert severity="error">{error}</Alert>;if(!data)return <Box py={8} textAlign="center"><CircularProgress/></Box>;
 const trend=data.sales_trend.change_percent;return <Stack spacing={2.5}>
  <Box><Stack direction="row" alignItems="center" gap={1}><AnalyticsIcon color="secondary"/><Typography variant="h4" fontWeight={900} sx={{fontSize:{xs:24,sm:30}}}>Akıllı Analizler</Typography></Stack><Typography color="text.secondary">İşletme verilerinden otomatik oluşturulan aksiyon önerileri · {new Date(data.generated_at).toLocaleString('tr-TR')}</Typography></Box>
  <Grid container spacing={1.5}><Grid size={{xs:12,sm:4}}><Card><CardContent><Typography color="text.secondary" variant="caption" fontWeight={800}>SON 30 GÜN SATIŞ</Typography><Typography variant="h5" fontWeight={900}>{money(data.sales_trend.current_30_days)}</Typography><Chip sx={{mt:1}} color={trend===null?'default':trend>=0?'success':'error'} label={trend===null?'Karşılaştırma yok':`${trend>=0?'+':''}%${trend}`}/></CardContent></Card></Grid><Grid size={{xs:12,sm:4}}><Card><CardContent><Typography color="text.secondary" variant="caption" fontWeight={800}>GECİKMİŞ ALACAK</Typography><Typography variant="h5" fontWeight={900}>{money(data.overdue.total)}</Typography><Typography color="text.secondary">{data.overdue.count} belge</Typography></CardContent></Card></Grid><Grid size={{xs:12,sm:4}}><Card><CardContent><Typography color="text.secondary" variant="caption" fontWeight={800}>PASİF MÜŞTERİ</Typography><Typography variant="h5" fontWeight={900}>{data.inactive_customers.length}</Typography><Typography color="text.secondary">60 gündür satış yok</Typography></CardContent></Card></Grid></Grid>
  <Card><CardContent><Typography variant="h6" fontWeight={900} mb={1.5}>Önerilen Aksiyonlar</Typography><Stack spacing={1}>{data.recommendations.map((r,i)=><Alert key={i} severity={r.severity} onClick={()=>nav(r.path)} sx={{cursor:'pointer'}}><Typography fontWeight={800}>{r.title}</Typography><Typography variant="body2">{r.detail}</Typography></Alert>)}</Stack></CardContent></Card>
  <Grid container spacing={2}><Grid size={{xs:12,lg:4}}><Card sx={{height:'100%'}}><CardContent><Typography variant="h6" fontWeight={900} mb={1.5}>Kritik Stoklar</Typography><Stack spacing={1}>{data.critical_products.length===0?<Typography color="text.secondary">Kritik ürün yok.</Typography>:data.critical_products.map(p=><Box key={p.id}><Stack direction="row" justifyContent="space-between"><Typography variant="body2" fontWeight={700}>{p.name}</Typography><Typography variant="body2" color="error">{p.stock} {p.unit}</Typography></Stack><LinearProgress color="error" variant="determinate" value={Math.max(4,Math.min(100,(Number(p.stock||0)/Math.max(1,Number(p.critical_level||1)))*100))}/></Box>)}</Stack></CardContent></Card></Grid><Grid size={{xs:12,lg:4}}><Card sx={{height:'100%'}}><CardContent><Typography variant="h6" fontWeight={900} mb={1.5}>60 Gündür Satış Yapılmayanlar</Typography><Stack spacing={1}>{data.inactive_customers.slice(0,10).map(c=><Box key={c.id} onClick={()=>nav(`/musteriler/${c.id}`)} sx={{cursor:'pointer',pb:1,borderBottom:'1px solid',borderColor:'divider'}}><Typography fontWeight={700}>{c.name}</Typography><Typography variant="caption" color="text.secondary">{c.last_sale_date?`Son satış: ${c.last_sale_date}`:'Satış kaydı yok'}</Typography></Box>)}</Stack></CardContent></Card></Grid><Grid size={{xs:12,lg:4}}><Card sx={{height:'100%'}}><CardContent><Typography variant="h6" fontWeight={900} mb={1.5}>Tahmini En Kârlı Ürünler</Typography><Stack spacing={1}>{data.profitable_products.map((p,i)=><Stack key={p.id||i} direction="row" justifyContent="space-between" gap={2}><Box><Typography fontWeight={700} variant="body2">{p.name||'Silinmiş ürün'}</Typography><Typography variant="caption" color="text.secondary">{Number(p.quantity||0).toLocaleString('tr-TR')} adet</Typography></Box><Typography fontWeight={900}>{money(p.estimated_profit)}</Typography></Stack>)}</Stack></CardContent></Card></Grid></Grid>
 </Stack>}
