import React from 'react';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Alert,Autocomplete,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Stack,TextField,Tooltip,Typography} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';import DeleteIcon from '@mui/icons-material/Delete';import EditIcon from '@mui/icons-material/Edit';import LockIcon from '@mui/icons-material/Lock';import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import {GridColDef} from '@mui/x-data-grid';import ResponsiveTable from '../components/ResponsiveTable';
import ExcelImportDialog from '../components/ExcelImportDialog';
import UploadFileIcon from '@mui/icons-material/UploadFile';import {api,money} from '../api';

const methods=[['cash','Nakit'],['card','Kart / POS'],['bank_transfer','Havale / EFT'],['credit','Vadeli'],['check','Çek'],['promissory_note','Senet']];

export default function Payments(){
 const nav=useNavigate();
 const [rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState<any>({customer_total:0,supplier_total:0,manual_total:0,document_total:0,movement_count:0}),[accounts,setAccounts]=useState<any[]>([]),[accountId,setAccountId]=useState<any>(''),[open,setOpen]=useState(false),[editId,setEditId]=useState<number|null>(null),[type,setType]=useState('customer'),[entities,setEntities]=useState<any[]>([]),[entity,setEntity]=useState<any|null>(null),[amount,setAmount]=useState(0),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[note,setNote]=useState(''),[paymentMethod,setPaymentMethod]=useState('cash'),[error,setError]=useState(''),[q,setQ]=useState(''),[filterType,setFilterType]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[methodFilter,setMethodFilter]=useState(''),[source,setSource]=useState(''),[sort,setSort]=useState('date_desc'),[loading,setLoading]=useState(false);
 const seq=useRef(0);
 const load=()=>{const current=++seq.current;setLoading(true);setError('');const params={q,entity_type:filterType||undefined,date_from:dateFrom||undefined,date_to:dateTo||undefined,payment_method:methodFilter||undefined,source:source||undefined,sort};Promise.all([api.get('/payments',{params}),api.get('/payments/summary',{params:{date_from:dateFrom||undefined,date_to:dateTo||undefined}})]).then(([list,stats])=>{if(current!==seq.current)return;setRows(list.data);setSummary(stats.data)}).catch(e=>{if(current===seq.current)setError(e.response?.data?.detail||'Tahsilat/ödeme listesi yüklenemedi.')}).finally(()=>{if(current===seq.current)setLoading(false)})};
 useEffect(()=>{const t=setTimeout(load,220);return()=>clearTimeout(t)},[q,filterType,dateFrom,dateTo,methodFilter,source,sort]);
 useEffect(()=>{api.get('/payments/accounts',{params:{active_only:true}}).then(r=>setAccounts(r.data)).catch(()=>setAccounts([]))},[]);
 useEffect(()=>{if(!open)return;api.get(type==='customer'?'/customers':'/suppliers').then(r=>{setEntities(r.data);if(editId)setEntity(r.data.find((x:any)=>x.id===entity?.id)||entity)})},[open,type]);
 const startNew=()=>{setEditId(null);setType('customer');setEntity(null);setAmount(0);setDate(new Date().toISOString().slice(0,10));setNote('');setPaymentMethod('cash');setAccountId('');setError('');setOpen(true)};
 const startEdit=(r:any)=>{if(r.is_document_payment)return;setEditId(r.id);setType(r.entity_type);setEntity({id:r.entity_id,name:r.entity_name});setAmount(Number(r.amount));setDate(r.payment_date);setNote(r.note||'');setPaymentMethod(r.payment_method||'cash');setAccountId(r.account_id||'');setError('');setOpen(true)};
 const remove=async(r:any)=>{if(r.is_document_payment){setError('Belgeye bağlı otomatik hareket belge üzerinden silinmelidir.');return}try{await api.delete(`/payments/${r.id}`);load()}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 const openEntity=(r:any)=>nav(r.entity_type==='customer'?`/musteriler/${r.entity_id}`:`/tedarikciler/${r.entity_id}`);
 const columns=useMemo<GridColDef[]>(()=>[
  {field:'id',headerName:'No',width:70},
  {field:'payment_date',headerName:'Tarih',width:125},
  {field:'entity_type',headerName:'Tür',width:105,valueFormatter:v=>v==='customer'?'Tahsilat':'Ödeme'},
  {field:'entity_name',headerName:'Cari',flex:1,minWidth:220,renderCell:p=><Button color="inherit" endIcon={<OpenInNewIcon fontSize="small"/>} onClick={e=>{e.stopPropagation();openEntity(p.row)}} sx={{textTransform:'none',fontWeight:800}}>{p.value}</Button>},
  {field:'payment_method',headerName:'Yöntem',width:140,valueFormatter:v=>methods.find(x=>x[0]===v)?.[1]||v},
  {field:'amount',headerName:'Tutar',width:145,valueFormatter:v=>money(v)},
  {field:'reference_type',headerName:'Kaynak',width:115,renderCell:p=>p.row.is_document_payment?<Chip size="small" icon={<LockIcon/>} label="Belge"/>:<Chip size="small" label="Manuel"/>},
  {field:'note',headerName:'Not',width:220},
  {field:'actions',headerName:'',width:100,sortable:false,renderCell:p=><><Tooltip title={p.row.is_document_payment?'Belge üzerinden düzenlenir':'Düzenle'}><span><IconButton size="small" disabled={!!p.row.is_document_payment} onClick={e=>{e.stopPropagation();startEdit(p.row)}}><EditIcon fontSize="small"/></IconButton></span></Tooltip><Tooltip title={p.row.is_document_payment?'Belge üzerinden silinir':'Sil'}><span><IconButton size="small" color="error" disabled={!!p.row.is_document_payment} onClick={e=>{e.stopPropagation();remove(p.row)}}><DeleteIcon fontSize="small"/></IconButton></span></Tooltip></>}
 ],[]);
 const save=async()=>{try{setError('');if(!entity||amount<=0)throw new Error('Cari ve geçerli tutar girin.');const expected=({cash:'cash',card:'pos',bank_transfer:'bank'} as any)[paymentMethod];if(expected&&accountId){const selected=accounts.find((a:any)=>a.id===Number(accountId));if(!selected||selected.account_type!==expected)throw new Error('Seçilen finans hesabı ödeme yöntemiyle uyumlu değil.')}const payload={entity_type:type,entity_id:entity.id,amount,payment_date:date,note,payment_method:paymentMethod,account_id:accountId?Number(accountId):null};if(editId)await api.put(`/payments/${editId}`,payload);else await api.post('/payments',payload);setOpen(false);load()}catch(e:any){setError(e.response?.data?.detail||e.message)}};
 const [importOpen,setImportOpen]=useState(false);
 const clearFilters=()=>{setQ('');setFilterType('');setDateFrom('');setDateTo('');setMethodFilter('');setSource('');setSort('date_desc')};
 return <Stack spacing={2}>
  <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Typography variant="h4" fontWeight={900}>Tahsilat / Ödeme</Typography><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<UploadFileIcon/>} onClick={()=>setImportOpen(true)}>Excel&apos;den Tahsilat</Button><Button variant="contained" startIcon={<AddIcon/>} onClick={startNew}>Yeni Hareket</Button></Stack></Stack>
  {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
  <Stack direction={{xs:'column',md:'row'}} spacing={1}>{[
   ['Tahsilat Toplamı',summary.customer_total,'success.main'],['Ödeme Toplamı',summary.supplier_total,'error.main'],['Manuel Hareket',summary.manual_total,'primary.main'],['Belgeye Bağlı',summary.document_total,'warning.main']
  ].map(([label,value,color]:any)=><Card key={label} variant="outlined" sx={{flex:1}}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={900} color={color}>{money(value)}</Typography></CardContent></Card>)}</Stack>
  <Stack direction={{xs:'column',lg:'row'}} spacing={1} flexWrap="wrap"><TextField size="small" label="Cari ara" value={q} onChange={e=>setQ(e.target.value)} sx={{minWidth:{lg:260},flex:1}}/><TextField select size="small" label="Tür" value={filterType} onChange={e=>setFilterType(e.target.value)} sx={{minWidth:150}}><MenuItem value="">Tümü</MenuItem><MenuItem value="customer">Tahsilat</MenuItem><MenuItem value="supplier">Ödeme</MenuItem></TextField><TextField select size="small" label="Yöntem" value={methodFilter} onChange={e=>setMethodFilter(e.target.value)} sx={{minWidth:155}}><MenuItem value="">Tümü</MenuItem>{methods.map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField><TextField select size="small" label="Kaynak" value={source} onChange={e=>setSource(e.target.value)} sx={{minWidth:145}}><MenuItem value="">Tümü</MenuItem><MenuItem value="manual">Manuel</MenuItem><MenuItem value="document">Belge</MenuItem></TextField><TextField size="small" type="date" label="Başlangıç" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField size="small" type="date" label="Bitiş" value={dateTo} onChange={e=>setDateTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField select size="small" label="Sıralama" value={sort} onChange={e=>setSort(e.target.value)} sx={{minWidth:190}}><MenuItem value="date_desc">Tarih yeni → eski</MenuItem><MenuItem value="date_asc">Tarih eski → yeni</MenuItem><MenuItem value="amount_desc">Tutar yüksek → düşük</MenuItem><MenuItem value="amount_asc">Tutar düşük → yüksek</MenuItem><MenuItem value="entity_asc">Cari A → Z</MenuItem><MenuItem value="entity_desc">Cari Z → A</MenuItem></TextField><Button onClick={clearFilters}>Temizle</Button></Stack>
  <Typography variant="body2" color="text.secondary">{summary.movement_count||0} hareket</Typography>
  <ResponsiveTable rows={rows} columns={columns} loading={loading} onRowClick={openEntity} cardTitle={r=>r.entity_name} cardSubtitle={r=>`${r.entity_type==='customer'?'Tahsilat':'Ödeme'} · ${r.payment_date}`} cardFields={[{label:'Tutar',value:r=>money(r.amount)},{label:'Yöntem',value:r=>methods.find(x=>x[0]===r.payment_method)?.[1]||r.payment_method},{label:'Kaynak',value:r=>r.is_document_payment?'Belge':'Manuel'}]}/>
  <ExcelImportDialog open={importOpen} kind="payments" onClose={()=>setImportOpen(false)} onDone={load}/>
  <Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editId?'Hareket Düzenle':'Yeni Tahsilat / Ödeme'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField select label="İşlem Türü" value={type} onChange={e=>{setType(e.target.value);setEntity(null)}}><MenuItem value="customer">Müşteri Tahsilatı</MenuItem><MenuItem value="supplier">Tedarikçi Ödemesi</MenuItem></TextField><Autocomplete options={entities} value={entity} isOptionEqualToValue={(a,b)=>a.id===b.id} getOptionLabel={x=>x?.name||''} onChange={(_,v)=>setEntity(v)} renderInput={p=><TextField {...p} label="Cari"/>}/><TextField select label="Ödeme Yöntemi" value={paymentMethod} onChange={e=>{setPaymentMethod(e.target.value);setAccountId('')}}>{methods.map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField>{['cash','card','bank_transfer'].includes(paymentMethod)&&<TextField select label="Kasa / Banka / POS Hesabı" value={accountId} onChange={e=>setAccountId(e.target.value)}><MenuItem value="">Varsayılan Hesap</MenuItem>{accounts.filter((a:any)=>a.account_type===({cash:'cash',card:'pos',bank_transfer:'bank'} as any)[paymentMethod]).map((a:any)=><MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>)}</TextField>}<TextField label="Tutar" type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><TextField label="Tarih" type="date" value={date} onChange={e=>setDate(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Not" value={note} onChange={e=>setNote(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={save}>Kaydet</Button></DialogActions></Dialog>
 </Stack>
}
